# Generated by Django 6.0 on 2026-02-24 21:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0003_remove_employee_department_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.CharField(max_length=50, unique=True, verbose_name='Letter Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary')),
                ('probation_period', models.IntegerField(default=3, verbose_name='Probation Period (months)')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='Terms & Conditions')),
                ('issued_by', models.CharField(max_length=100, verbose_name='Issued By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrm.department', verbose_name='Department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrm.designation', verbose_name='Designation')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_letter', to='hrm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Appointment Letter',
                'verbose_name_plural': 'Appointment Letters',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Gratuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_service', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Years of Service')),
                ('last_basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Last Basic Salary')),
                ('gratuity_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Formula: (Last Basic × Years of Service × 2) / 12', max_digits=12, verbose_name='Gratuity Amount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gratuity', to='hrm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Gratuity',
                'verbose_name_plural': 'Gratuities',
            },
        ),
        migrations.CreateModel(
            name='Increment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_type', models.CharField(choices=[('annual', 'Annual Increment'), ('promotion', 'Promotion'), ('performance', 'Performance'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='Type')),
                ('previous_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Previous Salary')),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New Salary')),
                ('increment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Increment Amount')),
                ('increment_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Increment (%)')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('approved_by', models.CharField(max_length=100, verbose_name='Approved By')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='hrm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Increment',
                'verbose_name_plural': 'Increments',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ProvidentFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_contribution_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Employee Contribution (%)')),
                ('employer_contribution_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Employer Contribution (%)')),
                ('employee_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Employee Balance')),
                ('employer_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Employer Balance')),
                ('total_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Balance')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provident_fund', to='hrm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Provident Fund',
                'verbose_name_plural': 'Provident Funds',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('transfer', 'Transfer'), ('promotion', 'Promotion'), ('demotion', 'Demotion')], max_length=20, verbose_name='Type')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('approved_by', models.CharField(max_length=100, verbose_name='Approved By')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hrm.employee', verbose_name='Employee')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='hrm.department', verbose_name='From Department')),
                ('from_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='hrm.designation', verbose_name='From Designation')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='hrm.department', verbose_name='To Department')),
                ('to_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='hrm.designation', verbose_name='To Designation')),
            ],
            options={
                'verbose_name': 'Transfer/Promotion',
                'verbose_name_plural': 'Transfers/Promotions',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('verbal', 'Verbal Warning'), ('written', 'Written Warning'), ('show_cause', 'Show Cause Notice'), ('final', 'Final Warning')], max_length=20, verbose_name='Type')),
                ('warning_date', models.DateField(verbose_name='Warning Date')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('action_taken', models.TextField(blank=True, verbose_name='Action Taken')),
                ('issued_by', models.CharField(max_length=100, verbose_name='Issued By')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='hrm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Warning',
                'verbose_name_plural': 'Warnings',
                'ordering': ['-warning_date'],
            },
        ),
    ]
