# Generated by Django 6.0 on 2026-02-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='Location Accuracy (meters)'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='source',
            field=models.CharField(choices=[('adms', 'ADMS Push'), ('tcp', 'TCP/PyZK Pull'), ('mobile', 'Mobile App'), ('manual', 'Manual Entry')], default='adms', max_length=20, verbose_name='Source'),
        ),
    ]
