# Generated by Django 6.0 on 2026-02-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_attendancelog_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.designation', verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.shift', verbose_name='Shift'),
        ),
    ]
