# Generated by Django 6.0.3 on 2026-04-18 14:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_tenants', '0016_alter_permission_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('FLAT', 'ফ্ল্যাট'), ('GARAGE', 'গ্যারেজ'), ('SHOP', 'দোকান')], max_length=10)),
                ('property_number', models.CharField(help_text='ইউনিক নম্বর (যেমন: F-101, G-05, S-01)', max_length=50)),
                ('floor_number', models.CharField(blank=True, help_text='ফ্লোর নম্বর', max_length=20)),
                ('size_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='সাইজ (বর্গফুট)', max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, help_text='বেডরুম সংখ্যা', null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, help_text='বাথরুম সংখ্যা', null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='মাসিক ভাড়া', max_digits=12)),
                ('status', models.CharField(choices=[('VACANT', 'খালি'), ('OCCUPIED', 'ভাড়া দেওয়া'), ('MAINTENANCE', 'মেইনটেনেন্স')], default='VACANT', max_length=15)),
                ('description', models.TextField(blank=True, help_text='বিস্তারিত বর্ণনা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_properties', to='auth_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['property_type', 'property_number'],
            },
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='চুক্তি শুরুর তারিখ')),
                ('end_date', models.DateField(help_text='চুক্তি শেষের তারিখ')),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='মাসিক ভাড়া', max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='অ্যাডভান্স টাকা', max_digits=12)),
                ('advance_months', models.PositiveSmallIntegerField(default=0, help_text='অ্যাডভান্স কত মাসের')),
                ('service_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='সার্ভিস চার্জ', max_digits=12)),
                ('rent_due_date', models.PositiveSmallIntegerField(default=5, help_text='প্রতি মাসে ভাড়া পরিশোধের তারিখ (১-৩১)')),
                ('agreement_document', models.FileField(blank=True, help_text='চুক্তি ডকুমেন্ট (PDF)', null=True, upload_to='rental/agreements/')),
                ('status', models.CharField(choices=[('ACTIVE', 'সক্রিয়'), ('EXPIRED', 'মেয়াদ শেষ'), ('TERMINATED', 'বাতিল')], default='ACTIVE', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='অতিরিক্ত নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agreements', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='rental_management.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreements', to='auth_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Rental Agreement',
                'verbose_name_plural': 'Rental Agreements',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('RENT', 'ভাড়া'), ('ADVANCE', 'অ্যাডভান্স'), ('SERVICE_CHARGE', 'সার্ভিস চার্জ'), ('OTHER', 'অন্যান্য')], max_length=20)),
                ('payment_month', models.DateField(blank=True, help_text='যে মাসের জন্য পেমেন্ট (শুধু RENT এর জন্য)', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='পরিমাণ', max_digits=12)),
                ('payment_date', models.DateField(help_text='পেমেন্ট তারিখ')),
                ('payment_method', models.CharField(choices=[('CASH', 'ক্যাশ'), ('BANK_TRANSFER', 'ব্যাংক ট্রান্সফার'), ('CHEQUE', 'চেক'), ('MOBILE_BANKING', 'মোবাইল ব্যাংকিং')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='ট্রানজেকশন রেফারেন্স', max_length=255)),
                ('receipt_number', models.CharField(help_text='রিসিপ্ট নম্বর', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_payments', to='auth_tenants.tenant')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental_management.rentalagreement')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='নাম', max_length=255)),
                ('mobile_number', models.CharField(help_text='মোবাইল নম্বর', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='ইমেইল', max_length=254)),
                ('nid_number', models.CharField(blank=True, help_text='জাতীয় পরিচয়পত্র নম্বর', max_length=50)),
                ('permanent_address', models.TextField(blank=True, help_text='স্থায়ী ঠিকানা')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='জরুরি যোগাযোগ - নাম', max_length=255)),
                ('emergency_contact_number', models.CharField(blank=True, help_text='জরুরি যোগাযোগ - নম্বর', max_length=20)),
                ('occupation', models.CharField(blank=True, help_text='পেশা', max_length=255)),
                ('family_members_count', models.PositiveSmallIntegerField(default=1, help_text='পরিবারের সদস্য সংখ্যা')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='rental/tenants/photos/')),
                ('nid_photo_front', models.ImageField(blank=True, null=True, upload_to='rental/tenants/nid/')),
                ('nid_photo_back', models.ImageField(blank=True, null=True, upload_to='rental/tenants/nid/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rental_tenants', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_tenants', to='auth_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Rental Tenant',
                'verbose_name_plural': 'Rental Tenants',
                'ordering': ['name'],
                'unique_together': {('tenant', 'mobile_number')},
            },
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='rental_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='rental_management.rentaltenant'),
        ),
        migrations.AddField(
            model_name='property',
            name='current_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_property', to='rental_management.rentaltenant'),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('message_text', models.TextField()),
                ('message_type', models.CharField(choices=[('REMINDER', 'পেমেন্ট রিমাইন্ডার'), ('DUE_NOTICE', 'বকেয়া নোটিশ'), ('CONTRACT_EXPIRY', 'চুক্তি শেষ হওয়ার নোটিশ'), ('PAYMENT_RECEIVED', 'পেমেন্ট প্রাপ্তি'), ('CUSTOM', 'কাস্টম মেসেজ')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'পেন্ডিং'), ('SENT', 'পাঠানো হয়েছে'), ('FAILED', 'ব্যর্থ')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='rental_management.rentaltenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_sms_logs', to='auth_tenants.tenant')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_month', models.DateField(help_text='বকেয়া মাস')),
                ('due_amount', models.DecimalField(decimal_places=2, help_text='বকেয়া পরিমাণ', max_digits=12)),
                ('due_date', models.DateField(help_text='বকেয়া তারিখ')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='SMS রিমাইন্ডার পাঠানো হয়েছে')),
                ('reminder_count', models.PositiveSmallIntegerField(default=0, help_text='কতবার রিমাইন্ডার পাঠানো হয়েছে')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_due_payments', to='auth_tenants.tenant')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_payments', to='rental_management.rentalagreement')),
            ],
            options={
                'verbose_name': 'Due Payment',
                'verbose_name_plural': 'Due Payments',
                'ordering': ['-due_month'],
                'unique_together': {('agreement', 'due_month')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('tenant', 'property_number')},
        ),
    ]
