# Generated by Django 6.0.3 on 2026-04-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0002_user_avatar'),
        ('foundation', '0002_category_currency_taxtype_taxrate_unitofmeasure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Variant code — unique per workspace (e.g. SKU-RED-M).', max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='foundation.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foundation_product_variants', to='auth_tenants.tenant')),
            ],
            options={
                'ordering': ['product', 'code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
