# Generated by Django 6.0.3 on 2026-04-08 17:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_unit_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Default inventory / standard cost per unit (used on documents).', max_digits=18),
        ),
        migrations.AddField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Suggested selling price per unit (reference).', max_digits=18),
        ),
    ]
