# Generated by Django 6.0.3 on 2026-04-09 07:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoice',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
    ]
