# Generated by Django 6.0.3 on 2026-04-09 07:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0002_user_avatar'),
        ('finance', '0002_apinvoice_shipping_charge_arinvoice_shipping_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='finance.apinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.appayment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_ap_payment_allocations', to='auth_tenants.tenant')),
            ],
            options={
                'unique_together': {('payment', 'invoice')},
            },
        ),
        migrations.CreateModel(
            name='ARReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_allocations', to='finance.arinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.arreceipt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_ar_receipt_allocations', to='auth_tenants.tenant')),
            ],
            options={
                'unique_together': {('receipt', 'invoice')},
            },
        ),
    ]
