# Generated by Django 6.0.3 on 2026-04-09 08:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_appaymentallocation_arreceiptallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appayment',
            name='ap_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_payments', to='finance.apinvoice'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='unapplied_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='arreceipt',
            name='ar_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_receipts', to='finance.arinvoice'),
        ),
        migrations.AddField(
            model_name='arreceipt',
            name='unapplied_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
    ]
