# Generated by Django 6.0.3 on 2026-04-14 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_tenants', '0012_screenhot_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('check_out', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activity_status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('away', 'Away')], default='active', max_length=20)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='auth_tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenhot_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in', '-id'],
                'indexes': [models.Index(fields=['tenant', 'user', '-check_in'], name='screenhot_a_tenant__0fc249_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('check_out__isnull', True)), fields=('tenant', 'user'), name='screenhot_unique_open_attendance_per_tenant_user')],
            },
        ),
        migrations.CreateModel(
            name='ScreenshotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='screenhot/screenshots/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('relative_path', models.CharField(blank=True, default='', max_length=512)),
                ('activity_status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('away', 'Away')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='auth_tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenhot_screenshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'user', '-captured_at'], name='screenhot_s_tenant__30aa6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('fps', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='screenhot/videos/%Y/%m/%d/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenhot_requested_video_jobs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenhot_video_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='auth_tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='screenhot_v_tenant__5eaad0_idx'), models.Index(fields=['tenant', 'target_user', '-created_at'], name='screenhot_v_tenant__89ceab_idx')],
            },
        ),
    ]
