# Generated by Django 6.0.3 on 2026-04-09 10:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_tenants', '0005_alter_tenantmodulesubscription_module_code'),
        ('foundation', '0004_product_price_warehouse_limits_line_totals'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('bom_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('total_component_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_boms', to='foundation.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='auth_tenants.tenant')),
            ],
            options={
                'ordering': ['-bom_date', '-id'],
                'unique_together': {('tenant', 'doc_no')},
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('scrap_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.billofmaterial')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='foundation.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='foundation.warehouse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('planned_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('produced_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('in_process', 'In process'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='production.billofmaterial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='foundation.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='auth_tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='foundation.warehouse')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
                'unique_together': {('tenant', 'doc_no')},
            },
        ),
        migrations.CreateModel(
            name='IssueForProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='auth_tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_issues', to='foundation.warehouse')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='production.productionorder')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
                'unique_together': {('tenant', 'doc_no')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('issued_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('returned_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='foundation.product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.productionorder')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='foundation.warehouse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IssueForProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='foundation.product')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.issueforproduction')),
                ('order_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_lines', to='production.productionordermaterial')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptFromProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=50)),
                ('receipt_date', models.DateField()),
                ('quantity_received', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='production.productionorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='auth_tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_receipts', to='foundation.warehouse')),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
                'unique_together': {('tenant', 'doc_no')},
            },
        ),
    ]
