# Generated by Django 6.0.3 on 2026-04-09 08:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0002_user_avatar'),
        ('foundation', '0004_product_price_warehouse_limits_line_totals'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=50)),
                ('return_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='purchase.goodsreceipt')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='foundation.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_rows', to='auth_tenants.tenant')),
            ],
            options={
                'ordering': ['-return_date', '-id'],
                'unique_together': {('tenant', 'doc_no')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('goods_receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_lines', to='purchase.goodsreceiptline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='foundation.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.purchasereturn')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.warehouse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
