# Generated by Django 6.0.3 on 2026-04-09 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_appayment_ap_invoice_appayment_unapplied_amount_and_more'),
        ('purchase', '0002_purchasereturn_purchasereturnline'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='finance_ap_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_goods_receipts', to='finance.apinvoice'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='finance_sync_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='finance_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
