# Generated by Django 6.0.4 on 2026-04-08 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0002_user_avatar'),
        ('hrm', '0002_holiday_notice_overtimerequest_attendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius_m', models.PositiveIntegerField(default=100, help_text='Allowed radius in meters.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('punch_time', models.DateTimeField(db_index=True)),
                ('punch_type', models.SmallIntegerField(choices=[(0, 'Check in'), (1, 'Check out'), (2, 'Break out'), (3, 'Break in'), (4, 'OT in'), (5, 'OT out'), (255, 'Punch')], default=0)),
                ('verify_type', models.SmallIntegerField(choices=[(0, 'Password'), (1, 'Fingerprint'), (2, 'Card'), (4, 'Card + fingerprint'), (6, 'Card + password'), (8, 'Card + FP + password'), (15, 'Face'), (20, 'Palm')], default=1)),
                ('work_code', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('adms', 'ADMS push'), ('tcp', 'TCP (PyZK)'), ('mobile', 'Mobile app'), ('manual', 'Manual')], default='adms', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_accuracy', models.FloatField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('mask_status', models.SmallIntegerField(default=0)),
                ('raw_data', models.TextField(blank=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-punch_time'],
            },
        ),
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('privilege', models.SmallIntegerField(default=0)),
                ('card_number', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('group', models.CharField(default='1', max_length=10)),
                ('has_fingerprint', models.BooleanField(default=False)),
                ('has_face', models.BooleanField(default=False)),
                ('has_palm', models.BooleanField(default=False)),
                ('fp_count', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['device', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TCPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('users', 'Users'), ('attendance', 'Attendance'), ('all', 'All')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('records_found', models.IntegerField(default=0)),
                ('records_synced', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZKDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('attendance', 'Attendance device'), ('access', 'Access control'), ('multi', 'Multi-function')], default='attendance', max_length=20)),
                ('connection_type', models.CharField(choices=[('adms', 'ADMS (push)'), ('tcp', 'TCP/IP (PyZK)'), ('both', 'ADMS + TCP')], default='adms', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(default=4370)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('push_version', models.CharField(blank=True, max_length=20)),
                ('oem_vendor', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user_count', models.IntegerField(default=0)),
                ('fp_count', models.IntegerField(default=0)),
                ('face_count', models.IntegerField(default=0)),
                ('palm_count', models.IntegerField(default=0)),
                ('transaction_count', models.IntegerField(default=0)),
                ('push_interval', models.IntegerField(default=30)),
                ('heartbeat_interval', models.IntegerField(default=60)),
                ('timezone_offset', models.IntegerField(default=360)),
                ('tcp_timeout', models.IntegerField(default=5)),
                ('tcp_password', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity', 'serial_number'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='zk_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='ZKTeco / device user_id — must match machine punches for this tenant.', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('zk_user_id__gt', '')), fields=('tenant', 'zk_user_id'), name='hrm_employee_unique_tenant_zk_user_id'),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_attendance_locations', to='auth_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='employeeattendancelocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_locations', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='employeeattendancelocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_links', to='hrm.attendancelocation'),
        ),
        migrations.AddField(
            model_name='zkdevice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_zk_devices', to='auth_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tcpsynclog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcp_sync_logs', to='hrm.zkdevice'),
        ),
        migrations.AddField(
            model_name='deviceuser',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_users', to='hrm.zkdevice'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='hrm.zkdevice'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelocation',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendancelocation',
            unique_together={('employee', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='deviceuser',
            unique_together={('device', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['user_id', 'punch_time'], name='hrm_attenda_user_id_e7cbdd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['device', 'created_at'], name='hrm_attenda_device__0099a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('device', 'user_id', 'punch_time')},
        ),
    ]
