# Generated by Django 6.0.4 on 2026-04-08 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_attendance_log_tenant(apps, schema_editor):
    AttendanceLog = apps.get_model("hrm", "AttendanceLog")
    ZKDevice = apps.get_model("hrm", "ZKDevice")
    for log in AttendanceLog.objects.filter(device_id__isnull=False):
        if log.tenant_id:
            continue
        dev = ZKDevice.objects.filter(pk=log.device_id).first()
        if dev:
            log.tenant_id = dev.tenant_id
            log.save(update_fields=["tenant_id"])


def _backfill_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0002_user_avatar'),
        ('hrm', '0003_zk_attendance_and_devices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_mode', models.CharField(choices=[('onsite_only', 'On-site only (must be inside a fence)'), ('hybrid', 'Hybrid (office + home zones)'), ('remote_allowed', 'Remote allowed (no fence if employee is remote)')], default='hybrid', max_length=20)),
                ('max_accuracy_meters', models.FloatField(default=100.0, help_text='Reject GPS reads worse than this (meters); 0 = ignore accuracy.')),
                ('early_checkin_minutes', models.PositiveIntegerField(default=60, help_text='Earliest check-in before location window opens.')),
                ('late_checkin_minutes', models.PositiveIntegerField(default=120, help_text='Latest check-in after location window ends.')),
                ('record_invalid_attempts', models.BooleanField(default=True, help_text='Store failed punches for audit / review.')),
                ('reject_api_when_invalid', models.BooleanField(default=False, help_text='If True, API returns error and does not save invalid punches.')),
                ('allow_remote_clock_without_gps', models.BooleanField(default=True, help_text='For remote employees: allow punch with no coordinates (logged as such).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='exclude_holidays',
            field=models.BooleanField(default=True, help_text='If True, punches blocked on tenant holiday calendar.'),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='location_kind',
            field=models.CharField(choices=[('office', 'Office / branch'), ('home', 'Home / remote zone'), ('other', 'Other site')], default='office', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='weekdays',
            field=models.CharField(default='0,1,2,3,4', help_text='Comma-separated weekday indices: 0=Mon … 6=Sun.', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelocation',
            name='window_start',
            field=models.TimeField(blank=True, help_text='If set, punch must be within window (tenant timezone).', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='distance_to_fence_m',
            field=models.FloatField(blank=True, help_text='Distance to nearest allowed fence (meters), if computed.', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_log_rows', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='matched_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_logs', to='hrm.attendancelocation'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='requires_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='review_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrm_attendance_logs', to='auth_tenants.tenant'),
        ),
        migrations.RunPython(_backfill_attendance_log_tenant, _backfill_reverse),
        migrations.AddField(
            model_name='attendancelog',
            name='validation_status',
            field=models.CharField(choices=[('valid', 'Valid'), ('device_sync', 'Device import (no GPS rule)'), ('out_of_geofence', 'Outside geofence'), ('low_accuracy', 'GPS accuracy too poor'), ('outside_time_window', 'Outside allowed time'), ('holiday_blocked', 'Holiday (location excludes)'), ('remote_no_gps', 'Remote clock without GPS'), ('pending_review', 'Pending admin review'), ('override_ok', 'Override approved')], default='device_sync', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location_mode',
            field=models.CharField(choices=[('office', 'Office-first (geofence required)'), ('hybrid', 'Hybrid (office + home zones)'), ('remote', 'Remote (policy allows clock without fence)')], default='office', help_text='Used with tenant GPS policy for mobile check-in.', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='hrm.zkdevice'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['tenant', 'punch_time'], name='hrm_attenda_tenant__be9a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['validation_status', 'requires_review'], name='hrm_attenda_validat_1947f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device', 'user_id', 'punch_time'), name='hrm_attlog_unique_device_punch'),
        ),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', True)), fields=('tenant', 'user_id', 'punch_time'), name='hrm_attlog_unique_tenant_mobile_punch'),
        ),
        migrations.AddField(
            model_name='locationattendancepolicy',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_location_policy', to='auth_tenants.tenant'),
        ),
    ]
