# Generated by Django 6.0.4 on 2026-04-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0002_user_avatar'),
        ('hrm', '0005_attendancelog_tenant_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text='Short code unique within the workspace, e.g. MORN, NIGHT.', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveSmallIntegerField(default=0, help_text='Unpaid break length inside the shift window.')),
                ('is_night_shift', models.BooleanField(default=False, help_text='Spans midnight or graveyard band — for reporting only.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_shifts', to='auth_tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftDateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_date_ranges', to='hrm.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_range_assignments', to='hrm.shift')),
            ],
            options={
                'ordering': ['-start_date', 'employee_id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='default_shift',
            field=models.ForeignKey(blank=True, help_text='Used when no weekly rule, date range, or one-day override applies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_as_default', to='hrm.shift'),
        ),
        migrations.CreateModel(
            name='EmployeeShiftWeekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Monday … 6=Sunday (same as date.weekday()).')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_weekday_rules', to='hrm.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_assignments', to='hrm.shift')),
            ],
            options={
                'ordering': ['employee_id', 'weekday'],
                'unique_together': {('employee', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_exceptions', to='hrm.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_assignments', to='hrm.shift')),
            ],
            options={
                'ordering': ['-date', 'employee_id'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
