# Generated by Django 6.0 on 2026-02-24 21:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_remove_employee_department_code_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('deduction_type', models.CharField(choices=[('absent', 'Absent Deduction'), ('late', 'Late Deduction'), ('early_out', 'Early Out Deduction')], max_length=20, verbose_name='Type')),
                ('calculation_method', models.CharField(choices=[('per_day', 'Per Day'), ('per_hour', 'Per Hour'), ('fixed', 'Fixed Amount')], default='per_day', max_length=20, verbose_name='Calculation Method')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Used only if calculation method is 'fixed'", max_digits=10, verbose_name='Fixed Amount')),
                ('grace_minutes', models.IntegerField(default=0, help_text='Grace period before deduction applies', verbose_name='Grace Minutes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deduction Rule',
                'verbose_name_plural': 'Deduction Rules',
                'ordering': ['deduction_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OvertimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Policy Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Policy Code')),
                ('regular_ot_rate', models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='e.g., 1.5 for time-and-a-half', max_digits=4, verbose_name='Regular OT Rate (multiplier)')),
                ('weekend_ot_rate', models.DecimalField(decimal_places=2, default=Decimal('2.0'), max_digits=4, verbose_name='Weekend OT Rate (multiplier)')),
                ('holiday_ot_rate', models.DecimalField(decimal_places=2, default=Decimal('2.0'), max_digits=4, verbose_name='Holiday OT Rate (multiplier)')),
                ('min_ot_hours', models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Minimum hours to qualify for OT payment', max_digits=4, verbose_name='Minimum OT Hours')),
                ('calculation_base', models.CharField(choices=[('basic', 'Basic Salary'), ('gross', 'Gross Salary')], default='basic', max_length=20, verbose_name='Calculation Base')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Overtime Policy',
                'verbose_name_plural': 'Overtime Policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Slab Name')),
                ('min_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Minimum Income')),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for unlimited', max_digits=12, null=True, verbose_name='Maximum Income')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tax Rate (%)')),
                ('fixed_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed tax for this slab', max_digits=12, verbose_name='Fixed Tax Amount')),
                ('financial_year', models.CharField(default='2024-2025', max_length=20, verbose_name='Financial Year')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Slab',
                'verbose_name_plural': 'Tax Slabs',
                'ordering': ['min_income'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days_per_month', models.IntegerField(default=26, verbose_name='Working Days/Month')),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8.0'), max_digits=4, verbose_name='Working Hours/Day')),
                ('pf_employee_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='PF Employee (%)')),
                ('pf_employer_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='PF Employer (%)')),
                ('enable_tax_deduction', models.BooleanField(default=False, verbose_name='Enable Tax Deduction')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absent_deduction_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absent_settings', to='payroll.deductionrule', verbose_name='Absent Deduction Rule')),
                ('late_deduction_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_settings', to='payroll.deductionrule', verbose_name='Late Deduction Rule')),
                ('overtime_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.overtimepolicy', verbose_name='Default OT Policy')),
            ],
            options={
                'verbose_name': 'Payroll Settings',
                'verbose_name_plural': 'Payroll Settings',
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount')),
                ('request_date', models.DateField(verbose_name='Request Date')),
                ('required_date', models.DateField(verbose_name='Required Date')),
                ('deduct_from_month', models.IntegerField(blank=True, null=True, verbose_name='Deduct From Month')),
                ('deduct_from_year', models.IntegerField(blank=True, null=True, verbose_name='Deduct From Year')),
                ('is_deducted', models.BooleanField(default=False, verbose_name='Deducted')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('deducted', 'Deducted')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Approved Date')),
                ('approved_by', models.CharField(blank=True, max_length=100, verbose_name='Approved By')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='hrm.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Salary Advance',
                'verbose_name_plural': 'Salary Advances',
                'ordering': ['-request_date'],
            },
        ),
    ]
