from django.urls import path

from . import views

app_name = "finance"

urlpatterns = [
    path("", views.FinanceDashboardView.as_view(), name="finance_dashboard"),
    path("guide/", views.FinanceGuideView.as_view(), name="finance_guide"),
    path("accounts/", views.AccountListView.as_view(), name="account_list"),
    path("accounts/add/", views.AccountCreateView.as_view(), name="account_create"),
    path("accounts/<int:pk>/edit/", views.AccountUpdateView.as_view(), name="account_edit"),
    path("accounts/<int:pk>/delete/", views.AccountDeleteView.as_view(), name="account_delete"),
    path("fiscal-years/", views.FiscalYearListView.as_view(), name="fiscal_year_list"),
    path("fiscal-years/add/", views.FiscalYearCreateView.as_view(), name="fiscal_year_create"),
    path("fiscal-years/<int:pk>/edit/", views.FiscalYearUpdateView.as_view(), name="fiscal_year_edit"),
    path("fiscal-years/<int:pk>/delete/", views.FiscalYearDeleteView.as_view(), name="fiscal_year_delete"),
    path("fiscal-periods/", views.FiscalPeriodListView.as_view(), name="fiscal_period_list"),
    path("fiscal-periods/add/", views.FiscalPeriodCreateView.as_view(), name="fiscal_period_create"),
    path("fiscal-periods/<int:pk>/edit/", views.FiscalPeriodUpdateView.as_view(), name="fiscal_period_edit"),
    path("fiscal-periods/<int:pk>/delete/", views.FiscalPeriodDeleteView.as_view(), name="fiscal_period_delete"),
    path("journals/", views.JournalEntryListView.as_view(), name="journal_list"),
    path("journals/add/", views.JournalEntryCreateView.as_view(), name="journal_create"),
    path("journals/<int:pk>/", views.JournalEntryDetailView.as_view(), name="journal_detail"),
    path("journals/<int:pk>/edit/", views.JournalEntryUpdateView.as_view(), name="journal_edit"),
    path("journals/<int:pk>/post/", views.JournalEntryPostView.as_view(), name="journal_post"),
    path("journals/<int:pk>/reverse/", views.JournalEntryReverseView.as_view(), name="journal_reverse"),
    path("reports/gl/", views.GeneralLedgerReportView.as_view(), name="report_gl"),
    path("reports/trial-balance/", views.TrialBalanceReportView.as_view(), name="report_trial_balance"),
    path("reports/profit-loss/", views.ProfitLossReportView.as_view(), name="report_profit_loss"),
    path("reports/balance-sheet/", views.BalanceSheetReportView.as_view(), name="report_balance_sheet"),
    path("reports/budget-vs-actual/", views.BudgetVsActualReportView.as_view(), name="report_budget_vs_actual"),
    path("ap/invoices/", views.APInvoiceListView.as_view(), name="ap_invoice_list"),
    path("ap/invoices/add/", views.APInvoiceCreateView.as_view(), name="ap_invoice_create"),
    path("ap/invoices/<int:pk>/post/", views.APInvoicePostView.as_view(), name="ap_invoice_post"),
    path("ap/payments/", views.APPaymentListView.as_view(), name="ap_payment_list"),
    path("ap/payments/add/", views.APPaymentCreateView.as_view(), name="ap_payment_create"),
    path("ap/payments/<int:pk>/post/", views.APPaymentPostView.as_view(), name="ap_payment_post"),
    path("ar/invoices/", views.ARInvoiceListView.as_view(), name="ar_invoice_list"),
    path("ar/invoices/add/", views.ARInvoiceCreateView.as_view(), name="ar_invoice_create"),
    path("ar/invoices/<int:pk>/post/", views.ARInvoicePostView.as_view(), name="ar_invoice_post"),
    path("ar/receipts/", views.ARReceiptListView.as_view(), name="ar_receipt_list"),
    path("ar/receipts/add/", views.ARReceiptCreateView.as_view(), name="ar_receipt_create"),
    path("ar/receipts/<int:pk>/post/", views.ARReceiptPostView.as_view(), name="ar_receipt_post"),
    path("cash/banks/", views.BankAccountListView.as_view(), name="bank_account_list"),
    path("cash/banks/add/", views.BankAccountCreateView.as_view(), name="bank_account_create"),
    path("cash/transactions/", views.CashTransactionListView.as_view(), name="cash_transaction_list"),
    path("cash/transactions/add/", views.CashTransactionCreateView.as_view(), name="cash_transaction_create"),
    path("cash/transactions/<int:pk>/post/", views.CashTransactionPostView.as_view(), name="cash_transaction_post"),
    path("assets/fixed/", views.FixedAssetListView.as_view(), name="fixed_asset_list"),
    path("assets/fixed/add/", views.FixedAssetCreateView.as_view(), name="fixed_asset_create"),
    path("assets/depreciations/", views.AssetDepreciationListView.as_view(), name="asset_depreciation_list"),
    path("assets/depreciations/add/", views.AssetDepreciationCreateView.as_view(), name="asset_depreciation_create"),
    path("assets/depreciations/<int:pk>/post/", views.AssetDepreciationPostView.as_view(), name="asset_depreciation_post"),
    path("budgets/", views.BudgetListView.as_view(), name="budget_list"),
    path("budgets/add/", views.BudgetCreateView.as_view(), name="budget_create"),
]

