# Generated by Django 6.0 on 2026-02-15 23:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Color Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Color Code')),
                ('hex_code', models.CharField(blank=True, help_text='e.g., #FF0000 for Red', max_length=7, verbose_name='Hex Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Size Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Size Code')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (smaller number appears first)', verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sku', models.CharField(help_text='Auto-generated: Product SKU + Size + Color', max_length=100, unique=True, verbose_name='Variant SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use product price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Purchase Price')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use product price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Selling Price')),
                ('min_stock_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Stock Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='erp.color', verbose_name='Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='erp.product', verbose_name='Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='erp.size', verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'size__sort_order', 'color__name'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariantWarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Quantity')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='erp.productvariant', verbose_name='Product Variant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_stocks', to='erp.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Product Variant Warehouse Stock',
                'verbose_name_plural': 'Product Variant Warehouse Stocks',
                'ordering': ['variant', 'warehouse'],
                'unique_together': {('variant', 'warehouse')},
            },
        ),
    ]
