# Generated by Django 6.0 on 2026-02-18 16:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_assetcategory_bankstatement_bankreconciliation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicksale',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='quicksale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quick_sales', to='erp.warehouse', verbose_name='Branch/Warehouse'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('allow_discount', models.BooleanField(default=True, verbose_name='Allow Discount')),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Max Discount %')),
                ('can_access_all_branches', models.BooleanField(default=False, help_text='If True, user can see data from all branches', verbose_name='Can Access All Branches')),
                ('branch', models.ForeignKey(blank=True, help_text="User's assigned branch/warehouse", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_users', to='erp.warehouse', verbose_name='Branch/Warehouse')),
                ('default_customer', models.ForeignKey(blank=True, help_text='Shop/Walk-in customer for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_users', to='erp.customer', verbose_name='Default Customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.DeleteModel(
            name='UserPOSProfile',
        ),
    ]
