# Generated by Django 6.0 on 2026-02-18 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_populate_branch_fields_high_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='goodsissue',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='inventorytransfer',
            name='from_branch',
        ),
        migrations.RemoveField(
            model_name='inventorytransfer',
            name='to_branch',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='branch',
        ),
        migrations.AddField(
            model_name='assetdepreciation',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this assetdepreciation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_depreciations', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this assetdisposal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_disposals', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this assetmaintenance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_maintenances', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this assettransfer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this bankreconciliation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_reconciliations', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this billofmaterials', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_of_materials', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='budget',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this budget', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this complaint', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this fixedasset', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this qualitycheck', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='qualitydefect',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this qualitydefect', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_defects', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this servicerequest', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this stocktransaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this bankstatement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptpo',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this goodsreceiptpo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_pos', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this incomingpayment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this journalentry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this outgoingpayment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_payments', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='purchasequotation',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this purchasequotation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_quotations', to='erp.warehouse', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/Warehouse for this salesquotation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotations', to='erp.warehouse', verbose_name='Branch'),
        ),
    ]
