# Generated by Django 6.0 on 2026-02-18 21:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_add_branch_fields_to_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch/Warehouse for this expense category', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='erp.warehouse', verbose_name='Branch')),
                ('default_account', models.ForeignKey(help_text='Default expense account for this category', on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='erp.chartofaccounts', verbose_name='Default Account')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='SimpleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expense_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Expense Number')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Expense Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch/Warehouse for this expense', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simple_expenses', to='erp.warehouse', verbose_name='Branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='erp.expensecategory', verbose_name='Expense Category')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('journal_entry', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_expense', to='erp.journalentry', verbose_name='Journal Entry')),
            ],
            options={
                'verbose_name': 'Simple Expense',
                'verbose_name_plural': 'Simple Expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
