# Generated by Django 6.0 on 2026-03-08 21:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_add_simple_expense_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksaleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Item-specific discount', max_digits=12, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='quicksaleitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Select variant if product has size/color options', null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.productvariant', verbose_name='Variant (Size/Color)'),
        ),
        migrations.AlterField(
            model_name='quicksale',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('reference_number', models.CharField(blank=True, help_text='bKash/Nagad TrxID বা card slip number', max_length=100, verbose_name='Reference / TrxID')),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash payment হলে cashier কত পেয়েছে', max_digits=12, verbose_name='Amount Received')),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash payment হলে ফেরত দেওয়া টাকা', max_digits=12, verbose_name='Change')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.paymentmethod', verbose_name='Payment Method')),
                ('quick_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp.quicksale', verbose_name='Quick Sale')),
            ],
            options={
                'verbose_name': 'POS Payment',
                'verbose_name_plural': 'POS Payments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('return_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='Return Number')),
                ('return_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Return Date & Time')),
                ('reason', models.TextField(blank=True, verbose_name='Return Reason')),
                ('total_refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total Refund')),
                ('refund_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('store_credit', 'Store Credit')], default='cash', max_length=20, verbose_name='Refund Method')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20, verbose_name='Status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_returns', to='erp.warehouse', verbose_name='Branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_returns', to=settings.AUTH_USER_MODEL, verbose_name='Cashier')),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='erp.quicksale', verbose_name='Original Sale')),
            ],
            options={
                'verbose_name': 'POS Return',
                'verbose_name_plural': 'POS Returns',
                'ordering': ['-return_datetime'],
            },
        ),
        migrations.CreateModel(
            name='POSReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Return Quantity')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Refund Amount')),
                ('restock', models.BooleanField(default=True, help_text='False করলে stock-এ ফেরত যাবে না (damaged item)', verbose_name='Add Back to Stock')),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.quicksaleitem', verbose_name='Original Sale Item')),
                ('pos_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.posreturn', verbose_name='POS Return')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='Product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.productvariant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'POS Return Item',
                'verbose_name_plural': 'POS Return Items',
            },
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('session_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='Session Number')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Opening Cash')),
                ('closing_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Closing Cash')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Expected Cash')),
                ('cash_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Cash Difference')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Opened At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='erp.warehouse', verbose_name='Branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Cashier')),
            ],
            options={
                'verbose_name': 'POS Session',
                'verbose_name_plural': 'POS Sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='quicksale',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional - link to POS session for cash management', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_sales', to='erp.possession', verbose_name='POS Session'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['cashier', 'status'], name='erp_possess_cashier_5efcab_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['branch', 'status'], name='erp_possess_branch__f0e568_idx'),
        ),
    ]
