# Generated by Django on 2025-03-09

from django.db import migrations, models
import django.db.models.deletion


def create_default_payment_methods(apps, schema_editor):
    """Create default payment methods"""
    PaymentMethod = apps.get_model('erp', 'PaymentMethod')
    
    methods = [
        {'code': 'cash', 'name': 'Cash', 'payment_type': 'cash'},
        {'code': 'card', 'name': 'Card', 'payment_type': 'card'},
        {'code': 'mobile', 'name': 'Mobile Payment', 'payment_type': 'mobile'},
        {'code': 'bank', 'name': 'Bank Transfer', 'payment_type': 'bank'},
    ]
    
    for method in methods:
        PaymentMethod.objects.get_or_create(
            code=method['code'],
            defaults={
                'name': method['name'],
                'payment_type': method['payment_type'],
                'is_active': True
            }
        )


def migrate_quicksale_payment_methods(apps, schema_editor):
    """Migrate QuickSale payment_method from CharField to ForeignKey"""
    QuickSale = apps.get_model('erp', 'QuickSale')
    PaymentMethod = apps.get_model('erp', 'PaymentMethod')
    db_alias = schema_editor.connection.alias
    
    # Get payment method objects
    payment_methods = {
        'cash': PaymentMethod.objects.using(db_alias).filter(code='cash').first(),
        'card': PaymentMethod.objects.using(db_alias).filter(code='card').first(),
        'mobile': PaymentMethod.objects.using(db_alias).filter(code='mobile').first(),
        'bank': PaymentMethod.objects.using(db_alias).filter(code='bank').first(),
    }
    
    # Default to cash if not found
    default_method = payment_methods.get('cash')
    if not default_method:
        default_method = PaymentMethod.objects.using(db_alias).first()
    
    # Use raw SQL to migrate data from old CharField to new ForeignKey
    if default_method:
        with schema_editor.connection.cursor() as cursor:
            # Map old string values to new PaymentMethod IDs
            for old_value, method_obj in payment_methods.items():
                if method_obj:
                    cursor.execute(
                        f"UPDATE erp_quicksale SET payment_method_new_id = %s WHERE payment_method_old = %s",
                        [method_obj.id, old_value]
                    )
            
            # Set default for any NULL or unmapped values
            cursor.execute(
                f"UPDATE erp_quicksale SET payment_method_new_id = %s WHERE payment_method_new_id IS NULL",
                [default_method.id]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_add_advanced_pos_features'),
    ]

    operations = [
        # Step 1: Create default payment methods
        migrations.RunPython(create_default_payment_methods, reverse_code=migrations.RunPython.noop),
        
        # Step 2: Rename old field to temporary name
        migrations.RenameField(
            model_name='quicksale',
            old_name='payment_method',
            new_name='payment_method_old',
        ),
        
        # Step 3: Add new ForeignKey field
        migrations.AddField(
            model_name='quicksale',
            name='payment_method_new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='quick_sales_new',
                to='erp.paymentmethod',
                verbose_name='Payment Method'
            ),
        ),
        
        # Step 4: Migrate data from old CharField to new ForeignKey
        migrations.RunPython(migrate_quicksale_payment_methods, reverse_code=migrations.RunPython.noop),
        
        # Step 5: Remove old CharField
        migrations.RemoveField(
            model_name='quicksale',
            name='payment_method_old',
        ),
        
        # Step 6: Rename new field to final name
        migrations.RenameField(
            model_name='quicksale',
            old_name='payment_method_new',
            new_name='payment_method',
        ),
        
        # Step 7: Update field with final configuration
        migrations.AlterField(
            model_name='quicksale',
            name='payment_method',
            field=models.ForeignKey(
                blank=True,
                help_text='Primary payment method for this sale',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='quick_sales',
                to='erp.paymentmethod',
                verbose_name='Payment Method'
            ),
        ),
    ]
