# Generated by Django 6.0 on 2026-03-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_add_tax_shipping_due_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingarea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
    ]
