# Generated by Django 6.0.4 on 2026-05-05 07:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_tenants', '0001_initial'),
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(editable=False, max_length=50)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('issue_type', models.CharField(choices=[('sales', 'Sales / delivery'), ('production', 'Production'), ('transfer', 'Transfer out'), ('damage', 'Damage / loss'), ('internal', 'Internal use')], default='sales', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('issued_to', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('stock_posted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_goods_issues', to='foundation.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_goods_issues', to='auth_tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_goods_issues', to='foundation.warehouse')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
                'unique_together': {('tenant', 'issue_number')},
            },
        ),
        migrations.CreateModel(
            name='GoodsIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=18)),
                ('line_no', models.PositiveSmallIntegerField(default=0)),
                ('goods_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.goodsissue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_goods_issue_items', to='foundation.product')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(editable=False, max_length=50)),
                ('transfer_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('stock_posted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfers_out', to='foundation.warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transfers', to='auth_tenants.tenant')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfers_in', to='foundation.warehouse')),
            ],
            options={
                'ordering': ['-transfer_date', '-id'],
                'unique_together': {('tenant', 'transfer_number')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=18)),
                ('line_no', models.PositiveSmallIntegerField(default=0)),
                ('inventory_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorytransfer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfer_items', to='foundation.product')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(editable=False, max_length=50)),
                ('adjustment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('adjustment_type', models.CharField(choices=[('opening', 'Opening stock'), ('physical_count', 'Physical count'), ('damage', 'Damage / loss'), ('correction', 'Correction'), ('write_off', 'Write-off'), ('found', 'Found / recovered')], default='physical_count', max_length=20)),
                ('warehouse_code', models.CharField(blank=True, db_index=True, default='', help_text='Warehouse code (snapshot; validated against master at save/post).', max_length=50)),
                ('warehouse_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('requested_by', models.CharField(blank=True, max_length=120)),
                ('total_increase', models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=18)),
                ('total_decrease', models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, help_text='Sum of absolute line value impacts (|Δqty| × unit cost).', max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_adjustments', to='auth_tenants.tenant')),
            ],
            options={
                'ordering': ['-adjustment_date', '-id'],
                'unique_together': {('tenant', 'adjustment_number')},
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(blank=True, db_index=True, default='', help_text='Product SKU (snapshot; validated against master at save/post).', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('system_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=18)),
                ('counted_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Physical count or new quantity after adjustment.', max_digits=18)),
                ('quantity_difference', models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('value_difference', models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, help_text='|Quantity difference| × unit cost.', max_digits=18)),
                ('line_reason', models.CharField(blank=True, max_length=200)),
                ('line_no', models.PositiveSmallIntegerField(default=0)),
                ('stock_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockadjustment')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Absolute quantity moved in the direction of transaction_type.', max_digits=18)),
                ('qty_signed', models.DecimalField(decimal_places=8, help_text='Signed change to on-hand stock (+ increase, − decrease).', max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('source_document_type', models.CharField(blank=True, choices=[('stock_adjustment', 'Stock adjustment'), ('goods_issue', 'Goods issue'), ('inventory_transfer', 'Inventory transfer'), ('manual', 'Manual / opening')], max_length=40)),
                ('source_document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_transactions', to='foundation.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_transactions', to='foundation.productvariant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_transactions', to='auth_tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_transactions', to='foundation.warehouse')),
            ],
            options={
                'verbose_name': 'Stock transaction',
                'verbose_name_plural': 'Stock transactions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=8, help_text='Optional reorder / minimum stock level for this warehouse.', max_digits=18, null=True)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=8, help_text='Optional maximum stock target for this warehouse.', max_digits=18, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_warehouse_stocks', to='foundation.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_warehouse_stocks', to='auth_tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_warehouse_stocks', to='foundation.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse stock',
                'verbose_name_plural': 'Warehouse stock',
                'ordering': ['warehouse', 'product'],
                'unique_together': {('tenant', 'product', 'warehouse')},
            },
        ),
    ]
