# Generated by Django 6.0.3 on 2026-04-08 17:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='total_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, help_text='Sum of absolute line value impacts (|Δqty| × unit cost).', max_digits=18),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='line_total',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, help_text='|Quantity difference| × unit cost.', max_digits=18),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='max_quantity',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Optional maximum stock target for this warehouse.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='min_quantity',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Optional reorder / minimum stock level for this warehouse.', max_digits=18, null=True),
        ),
    ]
