# Generated by Django 6.0.4 on 2026-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_adjustment_denorm_warehouse_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='warehouse_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Warehouse code (snapshot; validated against master at save/post).', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockadjustmentitem',
            name='product_sku',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Product SKU (snapshot; validated against master at save/post).', max_length=100),
        ),
    ]
