# Generated by Django 6.0.4 on 2026-04-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockadjustment_warehouse_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantWarehouseStock',
        ),
    ]
