from django.urls import include, path

from . import employee_portal_views, geo_views, shift_views, views, zk_views

app_name = "hrm"

urlpatterns = [
    path("recruitment/", include("recruitment.urls")),
    # Shifts & roster
    path("shifts/", shift_views.shift_list, name="shift_list"),
    path("shifts/add/", shift_views.shift_create, name="shift_create"),
    path("shifts/<int:pk>/edit/", shift_views.shift_edit, name="shift_edit"),
    path("shifts/<int:pk>/delete/", shift_views.shift_delete, name="shift_delete"),
    path("shifts/guide/", shift_views.shift_management_guide, name="shift_management_guide"),
    path("roster/weekday/", shift_views.roster_weekday_list, name="roster_weekday_list"),
    path("roster/weekday/add/", shift_views.roster_weekday_create, name="roster_weekday_create"),
    path("roster/weekday/<int:pk>/edit/", shift_views.roster_weekday_edit, name="roster_weekday_edit"),
    path("roster/weekday/<int:pk>/delete/", shift_views.roster_weekday_delete, name="roster_weekday_delete"),
    path("roster/ranges/", shift_views.roster_range_list, name="roster_range_list"),
    path("roster/ranges/add/", shift_views.roster_range_create, name="roster_range_create"),
    path("roster/ranges/<int:pk>/edit/", shift_views.roster_range_edit, name="roster_range_edit"),
    path("roster/ranges/<int:pk>/delete/", shift_views.roster_range_delete, name="roster_range_delete"),
    path("roster/exceptions/", shift_views.roster_exception_list, name="roster_exception_list"),
    path("roster/exceptions/add/", shift_views.roster_exception_create, name="roster_exception_create"),
    path("roster/exceptions/<int:pk>/edit/", shift_views.roster_exception_edit, name="roster_exception_edit"),
    path("roster/exceptions/<int:pk>/delete/", shift_views.roster_exception_delete, name="roster_exception_delete"),
    path("roster/bulk/", shift_views.roster_bulk, name="roster_bulk"),
    path("roster/bulk/apply/", shift_views.roster_bulk_apply, name="roster_bulk_apply"),
    path("roster/preview/", shift_views.roster_preview, name="roster_preview"),
    path(
        "set-active-tenant/",
        views.set_active_hrm_tenant,
        name="set_active_tenant",
    ),
    path(
        "me/check-in/",
        employee_portal_views.EmployeeCheckinView.as_view(),
        name="employee_checkin",
    ),
    path(
        "me/leave/",
        employee_portal_views.EmployeeLeaveSubmitView.as_view(),
        name="employee_leave_submit",
    ),
    path(
        "me/",
        employee_portal_views.EmployeeDashboardView.as_view(),
        name="employee_home",
    ),
    path("", views.hrm_dashboard, name="hrm_dashboard"),
    path(
        "api/employees/search/",
        views.HrmEmployeeSearchAPIView.as_view(),
        name="api_employee_search",
    ),
    path(
        "api/employees/picker/",
        views.HrmEmployeePickerAPIView.as_view(),
        name="api_employee_picker",
    ),
    path("departments/", views.department_list, name="department_list"),
    path("departments/add/", views.department_create, name="department_create"),
    path("departments/<int:pk>/edit/", views.department_edit, name="department_edit"),
    path("departments/<int:pk>/delete/", views.department_delete, name="department_delete"),
    path("job-titles/", views.job_title_list, name="job_title_list"),
    path("job-titles/add/", views.job_title_create, name="job_title_create"),
    path("job-titles/<int:pk>/edit/", views.job_title_edit, name="job_title_edit"),
    path("job-titles/<int:pk>/delete/", views.job_title_delete, name="job_title_delete"),
    path("employees/", views.employee_list, name="employee_list"),
    path("employees/add/", views.employee_create, name="employee_create"),
    path("employees/<int:pk>/edit/", views.employee_edit, name="employee_edit"),
    path("employees/<int:pk>/delete/", views.employee_delete, name="employee_delete"),
    path("leave-types/", views.leave_type_list, name="leave_type_list"),
    path("leave-types/add/", views.leave_type_create, name="leave_type_create"),
    path("leave-types/<int:pk>/edit/", views.leave_type_edit, name="leave_type_edit"),
    path("leave-types/<int:pk>/delete/", views.leave_type_delete, name="leave_type_delete"),
    path("leaves/", views.leave_request_list, name="leave_request_list"),
    path("leaves/<int:pk>/approve/", views.leave_request_approve, name="leave_request_approve"),
    path("leaves/<int:pk>/reject/", views.leave_request_reject, name="leave_request_reject"),
    path("holidays/", views.holiday_list, name="holiday_list"),
    path("holidays/add/", views.holiday_create, name="holiday_create"),
    path("holidays/<int:pk>/edit/", views.holiday_edit, name="holiday_edit"),
    path("holidays/<int:pk>/delete/", views.holiday_delete, name="holiday_delete"),
    path("notices/", views.notice_list, name="notice_list"),
    path("notices/add/", views.notice_create, name="notice_create"),
    path("notices/<int:pk>/edit/", views.notice_edit, name="notice_edit"),
    path("notices/<int:pk>/delete/", views.notice_delete, name="notice_delete"),
    path("zk/devices/", zk_views.zk_device_list, name="zk_device_list"),
    path("zk/devices/add/", zk_views.zk_device_create, name="zk_device_create"),
    path("zk/devices/<int:pk>/edit/", zk_views.zk_device_edit, name="zk_device_edit"),
    path("zk/devices/<int:pk>/delete/", zk_views.zk_device_delete, name="zk_device_delete"),
    path("zk/devices/<int:pk>/sync-users/", zk_views.zk_sync_users, name="zk_sync_users"),
    path("zk/devices/<int:pk>/sync-attendance/", zk_views.zk_sync_attendance, name="zk_sync_attendance"),
    path("zk/logs/", zk_views.zk_attendance_log_list, name="zk_attendance_log_list"),
    path("zk/locations/", zk_views.attendance_location_list, name="attendance_location_list"),
    path("zk/locations/add/", zk_views.attendance_location_create, name="attendance_location_create"),
    path("zk/locations/<int:pk>/edit/", zk_views.attendance_location_edit, name="attendance_location_edit"),
    path("zk/locations/<int:pk>/delete/", zk_views.attendance_location_delete, name="attendance_location_delete"),
    path("zk/policy/", geo_views.location_policy, name="location_policy"),
    path("zk/reports/locations/", geo_views.location_attendance_report, name="location_attendance_report"),
    path("zk/reviews/", geo_views.attendance_review_list, name="attendance_review_list"),
    path("zk/reviews/<int:pk>/action/", geo_views.attendance_review_action, name="attendance_review_action"),
    path("attendance/", views.attendance_list, name="attendance_list"),
    path("attendance/add/", views.attendance_create, name="attendance_create"),
    path("attendance/bulk-action/", views.attendance_bulk_action, name="attendance_bulk_action"),
    path("attendance/<int:pk>/edit/", views.attendance_edit, name="attendance_edit"),
    path("attendance/<int:pk>/delete/", views.attendance_delete, name="attendance_delete"),
    path("overtime/", views.overtime_list, name="overtime_list"),
    path("overtime/add/", views.overtime_create, name="overtime_create"),
    # Static paths must come before overtime/<int:pk>/… so names like bulk-action are not ambiguous.
    path("overtime/bulk-action/", views.overtime_bulk_action, name="overtime_bulk_action"),
    path("overtime/<int:pk>/edit/", views.overtime_edit, name="overtime_edit"),
    path("overtime/<int:pk>/delete/", views.overtime_delete, name="overtime_delete"),
    path("overtime/<int:pk>/approve/", views.overtime_approve, name="overtime_approve"),
    path("overtime/<int:pk>/reject/", views.overtime_reject, name="overtime_reject"),
]
