# Generated by Django 6.0.3 on 2026-04-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_remove_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultentry',
            name='account_identifier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags, e.g. prod, billing, api.', max_length=255),
        ),
    ]
