# Generated by Django 6.0.3 on 2026-04-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_vaultentry_account_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultentry',
            name='account_identifier',
        ),
        migrations.RemoveField(
            model_name='vaultentry',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='vaultentry',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='vaultentry',
            name='expires_on',
        ),
        migrations.RemoveField(
            model_name='vaultentry',
            name='tags',
        ),
    ]
