# Generated by Django 6.0.3 on 2026-04-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0014_vault_module'),
        ('foundation', '0004_product_price_warehouse_limits_line_totals'),
        ('jiraclone', '0006_projectdepartmentassignment_users'),
        ('vault', '0006_remove_vaultentry_account_identifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaultcategory',
            options={'ordering': ['customer__name', 'project__key', 'name']},
        ),
        migrations.AlterModelOptions(
            name='vaultentry',
            options={'ordering': ['category__customer__name', 'category__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='vaultcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vaultcategory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_categories', to='foundation.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='vaultcategory',
            unique_together={('tenant', 'customer', 'project', 'name')},
        ),
    ]
