# Generated by Django 6.0.3 on 2026-04-15 15:42

import django.db.models.deletion
from django.db import migrations, models


def backfill_entry_project_from_category(apps, schema_editor):
    VaultEntry = apps.get_model("vault", "VaultEntry")
    for entry in VaultEntry.objects.select_related("category").all():
        if entry.project_id is None and entry.category_id and getattr(entry.category, "project_id", None):
            entry.project_id = entry.category.project_id
            entry.save(update_fields=["project"])


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0014_vault_module'),
        ('foundation', '0004_product_price_warehouse_limits_line_totals'),
        ('jiraclone', '0006_projectdepartmentassignment_users'),
        ('vault', '0008_backfill_category_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaultcategory',
            options={'ordering': ['customer__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='vaultentry',
            options={'ordering': ['category__customer__name', 'project__key', 'category__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='vaultcategory',
            unique_together={('tenant', 'customer', 'name')},
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_entries', to='jiraclone.jiraproject'),
        ),
        migrations.RunPython(backfill_entry_project_from_category, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='vaultcategory',
            name='project',
        ),
    ]
