# Generated by Django 6.0 on 2026-02-16 00:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('costing_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Costing#')),
                ('version', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Version')),
                ('costing_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('fabric_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Fabric')),
                ('trim_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Trim')),
                ('embellishment_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Embellishment')),
                ('cm_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CM')),
                ('testing_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Testing')),
                ('commercial_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Commercial')),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Other')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Cost')),
                ('target_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Target Price')),
                ('quoted_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Quoted Price')),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Final Price')),
                ('margin_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Margin')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Margin%')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('approved_by', models.CharField(blank=True, max_length=100, verbose_name='Approved By')),
                ('approved_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Approved Date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garments.buyer')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garments.season')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costing_sheets', to='garments.style')),
            ],
            options={
                'verbose_name': 'Costing Sheet',
                'ordering': ['-costing_date'],
            },
        ),
        migrations.CreateModel(
            name='CostingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('component_type', models.CharField(choices=[('fabric', 'Fabric'), ('trim', 'Trim'), ('embellishment', 'Embellishment'), ('labor', 'Labor'), ('overhead', 'Overhead'), ('other', 'Other')], db_index=True, max_length=50, verbose_name='Type')),
                ('description', models.CharField(db_index=True, max_length=200, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Qty')),
                ('unit', models.CharField(default='PCS', max_length=20, verbose_name='Unit')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Cost')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('wastage_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Wastage%')),
                ('final_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Final Cost')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('costing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='garments.costingsheet')),
            ],
            options={
                'verbose_name': 'Costing Component',
                'ordering': ['costing_sheet', 'component_type', 'description'],
            },
        ),
        migrations.CreateModel(
            name='CostVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('variance_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('cost_category', models.CharField(choices=[('fabric', 'Fabric'), ('trim', 'Trim'), ('cm', 'CM'), ('overhead', 'Overhead'), ('other', 'Other')], db_index=True, max_length=50, verbose_name='Category')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budgeted')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Actual')),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Variance')),
                ('variance_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Variance%')),
                ('variance_type', models.CharField(choices=[('favorable', 'Favorable'), ('unfavorable', 'Unfavorable'), ('neutral', 'Neutral')], db_index=True, default='neutral', max_length=20, verbose_name='Type')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('action_taken', models.TextField(blank=True, verbose_name='Action')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_variances', to='garments.buyerorder')),
            ],
            options={
                'verbose_name': 'Cost Variance',
                'ordering': ['-variance_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('budgeted_fabric', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Budget Fabric')),
                ('budgeted_trim', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Budget Trim')),
                ('budgeted_cm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Budget CM')),
                ('budgeted_other', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Budget Other')),
                ('budgeted_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Budget Total')),
                ('actual_fabric', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Actual Fabric')),
                ('actual_trim', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Actual Trim')),
                ('actual_cm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Actual CM')),
                ('actual_other', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Actual Other')),
                ('actual_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Actual Total')),
                ('order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Order Value')),
                ('budgeted_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Budget Profit')),
                ('actual_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Actual Profit')),
                ('profit_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Variance')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('costing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garments.costingsheet')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_costing', to='garments.buyerorder')),
            ],
            options={
                'verbose_name': 'Order Costing',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('price_list_name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Price List')),
                ('price_list_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code')),
                ('currency', models.CharField(db_index=True, default='USD', max_length=10, verbose_name='Currency')),
                ('valid_from', models.DateField(db_index=True, verbose_name='Valid From')),
                ('valid_to', models.DateField(db_index=True, verbose_name='Valid To')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='garments.buyer')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garments.season')),
            ],
            options={
                'verbose_name': 'Price List',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price')),
                ('min_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min Qty')),
                ('max_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Qty')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount%')),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Final Price')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='garments.pricelist')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garments.style')),
            ],
            options={
                'verbose_name': 'Price List Item',
                'ordering': ['price_list', 'style'],
            },
        ),
        migrations.CreateModel(
            name='ProfitAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('analysis_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('analysis_type', models.CharField(choices=[('order', 'Order'), ('style', 'Style'), ('buyer', 'Buyer'), ('season', 'Season')], db_index=True, max_length=20, verbose_name='Type')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Revenue')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cost')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gross Profit')),
                ('gross_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Margin%')),
                ('quantity', models.IntegerField(default=0, verbose_name='Qty')),
                ('profit_per_piece', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Profit/Pc')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garments.buyer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garments.buyerorder')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garments.season')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garments.style')),
            ],
            options={
                'verbose_name': 'Profit Analysis',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='QuotationCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('quotation_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Quotation#')),
                ('quotation_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qty')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Cost')),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quoted Price')),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Value')),
                ('margin_per_piece', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Margin/Pc')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Margin%')),
                ('total_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Margin')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garments.buyer')),
                ('costing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garments.costingsheet')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garments.style')),
            ],
            options={
                'verbose_name': 'Quotation Costing',
                'ordering': ['-quotation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='costingsheet',
            index=models.Index(fields=['style', 'status'], name='garments_co_style_i_f85dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='costingsheet',
            index=models.Index(fields=['buyer', 'status'], name='garments_co_buyer_i_9de94e_idx'),
        ),
        migrations.AddIndex(
            model_name='costingsheet',
            index=models.Index(fields=['-costing_date'], name='garments_co_costing_0321b6_idx'),
        ),
        migrations.AddIndex(
            model_name='costingsheet',
            index=models.Index(fields=['status', 'approved_date'], name='garments_co_status_472d8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costingsheet',
            unique_together={('style', 'version')},
        ),
        migrations.AddIndex(
            model_name='costingcomponent',
            index=models.Index(fields=['costing_sheet', 'component_type'], name='garments_co_costing_e78540_idx'),
        ),
        migrations.AddIndex(
            model_name='costvariance',
            index=models.Index(fields=['order', 'cost_category'], name='garments_co_order_i_d4fa42_idx'),
        ),
        migrations.AddIndex(
            model_name='costvariance',
            index=models.Index(fields=['variance_type', 'variance_date'], name='garments_co_varianc_6b63df_idx'),
        ),
        migrations.AddIndex(
            model_name='costvariance',
            index=models.Index(fields=['-variance_date'], name='garments_co_varianc_a14825_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercosting',
            index=models.Index(fields=['order', 'last_updated'], name='garments_or_order_i_d6c357_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['buyer', 'is_active'], name='garments_pr_buyer_i_d656b2_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['season', 'is_active'], name='garments_pr_season__d2fc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['valid_from', 'valid_to'], name='garments_pr_valid_f_7aca10_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['price_list', 'style'], name='garments_pr_price_l_db8ec1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('price_list', 'style')},
        ),
        migrations.AddIndex(
            model_name='profitanalysis',
            index=models.Index(fields=['analysis_type', 'analysis_date'], name='garments_pr_analysi_8dc444_idx'),
        ),
        migrations.AddIndex(
            model_name='profitanalysis',
            index=models.Index(fields=['buyer', 'analysis_date'], name='garments_pr_buyer_i_13c6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='profitanalysis',
            index=models.Index(fields=['season', 'analysis_date'], name='garments_pr_season__655891_idx'),
        ),
        migrations.AddIndex(
            model_name='profitanalysis',
            index=models.Index(fields=['-analysis_date'], name='garments_pr_analysi_1ac085_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationcosting',
            index=models.Index(fields=['buyer', 'status'], name='garments_qu_buyer_i_1a1e49_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationcosting',
            index=models.Index(fields=['style', 'status'], name='garments_qu_style_i_8e36cb_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationcosting',
            index=models.Index(fields=['-quotation_date'], name='garments_qu_quotati_119621_idx'),
        ),
    ]
