"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def admin_changelist(app_label, model_name):
    """Helper function to generate admin changelist URL"""
    return lambda request: reverse_lazy(f"admin:{app_label}_{model_name}_changelist")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9ndkcy2!xmq^31o+t#+6#p8wn%#_$khp#%*zoe+&0xj32^_+am'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["erp.ezydream.com", "localhost", "127.0.0.1","*"]
# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    
    # Local apps
    'config',  # Config app for custom admin
    'erp',
    'hrm',
    # 'garments',  # Hidden - not in use
    # 'payroll',   # Hidden - not in use
    # 'compliance',  # Hidden - not in use
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'erp.context_processors.company_info',  # Add company info to all templates
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== CACHE CONFIGURATION ====================
# Using local memory cache for development, use Redis/Memcached in production
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'erp-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# ==================== DJANGO TASKS CONFIGURATION ====================
# Django 6.0 built-in task queue system
TASKS = {
    'default': {
        'BACKEND': 'django.tasks.backends.immediate.ImmediateBackend',
    }
}

# ==================== REST FRAMEWORK CONFIGURATION ====================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissions',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ==================== DRF SPECTACULAR (SWAGGER/REDOC) ====================
SPECTACULAR_SETTINGS = {
    'TITLE': 'ERP System API',
    'DESCRIPTION': 'Complete ERP System API with Sales, Purchase, Inventory, Manufacturing, HRM, and Accounting modules.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'TAGS': [
        {'name': 'Foundation', 'description': 'Company, Warehouses, Categories, Products, Customers, Suppliers'},
        {'name': 'Financial', 'description': 'Currencies, Tax, Payment Terms, Bank Accounts, Chart of Accounts'},
        {'name': 'Sales', 'description': 'Quotations, Orders, Deliveries, Invoices, Returns, Payments'},
        {'name': 'Purchase', 'description': 'Quotations, Orders, Goods Receipts, Invoices, Returns, Payments'},
        {'name': 'Manufacturing', 'description': 'Bill of Materials, Production Orders, Production Receipts'},
        {'name': 'Inventory', 'description': 'Stock Adjustments, Transfers, Warehouse Stock'},
        {'name': 'Accounting', 'description': 'Journal Entries, Budgets'},
        {'name': 'System', 'description': 'Discounts, Approvals, Notifications'},
    ],
}

# ==================== SIMPLE JWT CONFIGURATION ====================
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ==================== CORS CONFIGURATION ====================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    # Flutter Web
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    # Chrome DevTools
    "http://localhost:*",
]

# Allow all origins in development (for Flutter mobile/web testing)
CORS_ALLOW_ALL_ORIGINS = True  # Enable for development

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Unfold Admin Configuration
from erp_unfold_menus import (
    ERP_MENUS, HRM_MENUS, HRM_REPORT_MENUS,  # GARMENTS_MENUS, PAYROLL_MENUS, COMPLIANCE_MENUS,
    ALL_MENUS
)

UNFOLD = {
    "SITE_TITLE": "ERP Admin Panel",
    "SITE_HEADER": "ERP Administration",
    "SITE_URL": "/",
    "SITE_SYMBOL": "speed",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "config.settings.environment_callback",
    "COLORS": {
        "primary": {
            "50": "252 254 235",
            "100": "247 252 213",
            "200": "238 248 178",
            "300": "226 242 142",
            "400": "208 234 106",
            "500": "196 216 46",
            "600": "168 184 42",
            "700": "140 154 35",
            "800": "112 123 28",
            "900": "84 92 21",
            "950": "63 69 16",
        },
        "font": {
            "subtle-light": "115 115 115",
            "default-light": "75 85 99",
            "dark-light": "55 65 81",
            "subtle-dark": "156 163 175",
            "default-dark": "209 213 219",
            "dark-dark": "243 244 246",
        },
    },
    "SHOW_LANGUAGES": False,
    "SHOW_ADMIN_TOOLS": True,
    "SHOW_BREADCRUMBS": True,
    "THEME_TOGGLE": True,
    "FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: static("admin/img/favicon-32x32.png"),
        },
    ],
    "STYLES": [
        lambda request: static("admin/css/custom_sidebar.css") + "?v=14",
        lambda request: static("admin/css/custom_tabs.css") + "?v=14",
    ],
    "SCRIPTS": [],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            *ERP_MENUS,
            *HRM_MENUS,
            # *PAYROLL_MENUS,  # Hidden
            # *COMPLIANCE_MENUS,  # Hidden
            *HRM_REPORT_MENUS,
            # *GARMENTS_MENUS,  # Hidden
        ],
    },
}


def environment_callback(request):
    """Callback to show environment badge in admin"""
    return ["Development", "warning"]
