# Generated by Django 6.0.3 on 2026-04-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0004_alter_tenantmodulesubscription_module_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmodulesubscription',
            name='module_code',
            field=models.CharField(choices=[('hrm', 'HRM'), ('recruitment', 'Recruitment'), ('inventory', 'Inventory'), ('finance', 'Finance'), ('purchase', 'Purchase'), ('sales', 'Sales'), ('production', 'Production'), ('payroll', 'Payroll')], max_length=50),
        ),
    ]
