# Generated by Django 6.0.4 on 2026-04-09 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0005_alter_tenantmodulesubscription_module_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('inventory', 'Inventory'), ('finance', 'Finance'), ('purchase', 'Purchase'), ('sales', 'Sales'), ('production', 'Production'), ('hrm', 'HRM'), ('recruitment', 'Recruitment'), ('payroll', 'Payroll'), ('auth_tenants', 'Tenant Auth'), ('system', 'System')], max_length=50),
        ),
        migrations.CreateModel(
            name='TenantPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_grants', to='auth_tenants.permission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='auth_tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'permission')},
            },
        ),
    ]
