# Generated by Django 6.0.3 on 2026-04-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0006_alter_permission_category_tenantpermissiongrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown on inventory printouts and similar documents.', null=True, upload_to='tenant_logos/'),
        ),
    ]
