# Generated by Django 6.0.3 on 2026-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenants', '0009_pos_module_and_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('inventory', 'Inventory'), ('finance', 'Finance'), ('purchase', 'Purchase'), ('sales', 'Sales'), ('production', 'Production'), ('jiraclone', 'Jira clone'), ('chat', 'Chat'), ('pos', 'POS'), ('hrm', 'HRM'), ('recruitment', 'Recruitment'), ('payroll', 'Payroll'), ('auth_tenants', 'Tenant Auth'), ('system', 'System')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantmodulesubscription',
            name='module_code',
            field=models.CharField(choices=[('hrm', 'HRM'), ('recruitment', 'Recruitment'), ('inventory', 'Inventory'), ('finance', 'Finance'), ('purchase', 'Purchase'), ('sales', 'Sales'), ('production', 'Production'), ('jiraclone', 'Jira clone'), ('chat', 'Chat'), ('pos', 'POS'), ('payroll', 'Payroll')], max_length=50),
        ),
    ]
