# Generated by Django 6.0.3 on 2026-04-11 17:29

from django.conf import settings
from django.db import migrations, models


def copy_assignee_to_assignees(apps, schema_editor):
    Issue = apps.get_model("jiraclone", "Issue")
    for issue in Issue.objects.exclude(assignee_id__isnull=True).iterator():
        issue.assignees.add(issue.assignee_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("jiraclone", "0001_jiraclone_module_and_app"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                help_text="One or more people (like shared ownership).",
                related_name="jira_issues_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(copy_assignee_to_assignees, noop_reverse),
        migrations.RemoveField(
            model_name="issue",
            name="assignee",
        ),
    ]
