# Generated by Django 6.0.3 on 2026-04-14 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_product_price_warehouse_limits_line_totals'),
        ('hrm', '0006_shift_and_roster'),
        ('jiraclone', '0004_project_team_issue_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraproject',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_projects', to='foundation.customer'),
        ),
        migrations.CreateModel(
            name='ProjectDepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_project_assignments', to='hrm.department')),
                ('employees', models.ManyToManyField(blank=True, related_name='jira_department_assignments', to='hrm.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='jiraclone.jiraproject')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'department')},
            },
        ),
    ]
