# Generated by Django 6.0.3 on 2026-04-14 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiraclone', '0005_jiraproject_customer_projectdepartmentassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdepartmentassignment',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Tenant users directly assigned under this project department.', related_name='jira_department_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
